# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SQLite.swift', '~> 0.11.4'

  # Pods for Application

  target 'ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
